---
- name: Deploy Application to Kubernetes
  hosts: all
  become: yes
  tasks:

    - name: Ensure kubectl is configured for Minikube
      command: minikube kubectl -- get nodes
      register: kubectl_config
      failed_when: kubectl_config.rc != 0

    - name: Create Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: cw2-server-deployment
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: cw2-server
            template:
              metadata:
                labels:
                  app: cw2-server
              spec:
                containers:
                - name: cw2-server
                  image: ayaqub300/cw2-server:1.0
                  ports:
                  - containerPort: 8080

    - name: Create Kubernetes Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: cw2-server-service
          spec:
            selector:
              app: cw2-server
            type: NodePort
            ports:
              - protocol: TCP
                port: 8080
                targetPort: 8080
                nodePort: 30007  # You can choose a port between 30000-32767

    - name: Scale Deployment to 3 Replicas
      kubernetes.core.k8s:
        state: present
        kind: Deployment
        name: cw2-server-deployment
        namespace: default
        definition:
          spec:
            replicas: 3

    - name: Verify Deployment Pods are Running
      kubernetes.core.k8s_info:
        kind: Pod
        label_selectors:
          - "app=cw2-server"
      register: deployed_pods

    - name: Display Deployed Pods
      debug:
        var: deployed_pods.resources
