---
- name: Install Kubernetes and Minikube
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Kubernetes apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install kubectl
      apt:
        name: kubectl
        state: present
        update_cache: yes

    - name: Download Minikube binary
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Install conntrack (required by Minikube)
      apt:
        name: conntrack
        state: present

    - name: Start Minikube
      command: minikube start --driver=none
      args:
        creates: /home/ubuntu/.minikube
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"

    - name: Verify kubectl version
      command: kubectl version --client
      register: kubectl_version

    - name: Display kubectl version
      debug:
        msg: "{{ kubectl_version.stdout }}"
